// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartPriceStream(arg1) {
  return window['go']['main']['App']['StartPriceStream'](arg1);
}

export function StopPriceStream() {
  return window['go']['main']['App']['StopPriceStream']();
}
