// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: price.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PriceService_GetCurrentPrice_FullMethodName       = "/price.PriceService/GetCurrentPrice"
	PriceService_SubscribePriceUpdates_FullMethodName = "/price.PriceService/SubscribePriceUpdates"
	PriceService_SetPrice_FullMethodName              = "/price.PriceService/SetPrice"
)

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PriceService provides real-time price updates via server streaming.
type PriceServiceClient interface {
	// GetCurrentPrice returns the latest price once (unary).
	GetCurrentPrice(ctx context.Context, in *GetCurrentPriceRequest, opts ...grpc.CallOption) (*PriceUpdate, error)
	// SubscribePriceUpdates opens a stream; the server pushes a new message
	// whenever the price changes (real-time).
	SubscribePriceUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (PriceService_SubscribePriceUpdatesClient, error)
	// SetPrice sets the current price for a symbol (e.g. BTC). Persisted to DB; all subscribers get the update.
	SetPrice(ctx context.Context, in *SetPriceRequest, opts ...grpc.CallOption) (*PriceUpdate, error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) GetCurrentPrice(ctx context.Context, in *GetCurrentPriceRequest, opts ...grpc.CallOption) (*PriceUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceUpdate)
	err := c.cc.Invoke(ctx, PriceService_GetCurrentPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceServiceClient) SubscribePriceUpdates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (PriceService_SubscribePriceUpdatesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[0], PriceService_SubscribePriceUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &priceServiceSubscribePriceUpdatesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PriceService_SubscribePriceUpdatesClient interface {
	Recv() (*PriceUpdate, error)
	grpc.ClientStream
}

type priceServiceSubscribePriceUpdatesClient struct {
	grpc.ClientStream
}

func (x *priceServiceSubscribePriceUpdatesClient) Recv() (*PriceUpdate, error) {
	m := new(PriceUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *priceServiceClient) SetPrice(ctx context.Context, in *SetPriceRequest, opts ...grpc.CallOption) (*PriceUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceUpdate)
	err := c.cc.Invoke(ctx, PriceService_SetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServiceServer is the server API for PriceService service.
// All implementations must embed UnimplementedPriceServiceServer
// for forward compatibility
//
// PriceService provides real-time price updates via server streaming.
type PriceServiceServer interface {
	// GetCurrentPrice returns the latest price once (unary).
	GetCurrentPrice(context.Context, *GetCurrentPriceRequest) (*PriceUpdate, error)
	// SubscribePriceUpdates opens a stream; the server pushes a new message
	// whenever the price changes (real-time).
	SubscribePriceUpdates(*SubscribeRequest, PriceService_SubscribePriceUpdatesServer) error
	// SetPrice sets the current price for a symbol (e.g. BTC). Persisted to DB; all subscribers get the update.
	SetPrice(context.Context, *SetPriceRequest) (*PriceUpdate, error)
	mustEmbedUnimplementedPriceServiceServer()
}

// UnimplementedPriceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServer struct {
}

func (UnimplementedPriceServiceServer) GetCurrentPrice(context.Context, *GetCurrentPriceRequest) (*PriceUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPrice not implemented")
}
func (UnimplementedPriceServiceServer) SubscribePriceUpdates(*SubscribeRequest, PriceService_SubscribePriceUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePriceUpdates not implemented")
}
func (UnimplementedPriceServiceServer) SetPrice(context.Context, *SetPriceRequest) (*PriceUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrice not implemented")
}
func (UnimplementedPriceServiceServer) mustEmbedUnimplementedPriceServiceServer() {}

// UnsafePriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServer()
}

func RegisterPriceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServer) {
	s.RegisterService(&PriceService_ServiceDesc, srv)
}

func _PriceService_GetCurrentPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).GetCurrentPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceService_GetCurrentPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).GetCurrentPrice(ctx, req.(*GetCurrentPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceService_SubscribePriceUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).SubscribePriceUpdates(m, &priceServiceSubscribePriceUpdatesServer{ServerStream: stream})
}

type PriceService_SubscribePriceUpdatesServer interface {
	Send(*PriceUpdate) error
	grpc.ServerStream
}

type priceServiceSubscribePriceUpdatesServer struct {
	grpc.ServerStream
}

func (x *priceServiceSubscribePriceUpdatesServer) Send(m *PriceUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _PriceService_SetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).SetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceService_SetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).SetPrice(ctx, req.(*SetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceService_ServiceDesc is the grpc.ServiceDesc for PriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "price.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentPrice",
			Handler:    _PriceService_GetCurrentPrice_Handler,
		},
		{
			MethodName: "SetPrice",
			Handler:    _PriceService_SetPrice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePriceUpdates",
			Handler:       _PriceService_SubscribePriceUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "price.proto",
}
